apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cerebro-pv-claim
  labels:
    component: elk
    role: cerebro
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: cerebro
  labels:
    component: elk
    role: cerebro
spec:
  replicas: 1
  selector:
    component: elk
    role: cerebro
  template:
    metadata:
      labels:
        component: elk
        role: cerebro
    spec:
      containers:
      - name: cerebro
        image: carlosedp/elasticsearch-cerebro:0.7.3
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        volumeMounts:
        - name: database
          mountPath: /var/lib/cerebro
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: cerebro-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: cerebro
  labels:
    component: elk
    role: cerebro
spec:
  selector:
    component: elk
    role: cerebro
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 9000
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cerebro
  annotations:
    traefik.frontend.rule.type: PathPrefix
spec:
  rules:
  - host: cerebro.internal.carlosedp.com
    http:
      paths:
      - path: /
        backend:
          serviceName: cerebro
          servicePort: 80

