kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-exporter
  namespace: monitoring
  labels:
    k8s-app: elasticsearch-exporter
spec:
  selector:
    k8s-app: elasticsearch-exporter
  ports:
    - protocol: TCP
      port: 9108
      name: es-metrics
  type: ClusterIP

